server:
  address: 0.0.0.0  #?? ?? ??
  port: 8080 # ???? 8080
  servlet:
    session:
      tracking-modes: cookie

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:mysql://localhost:3306/halo_eventerDB
    username: halo-admin
    password: eventer2024
    driver-class-namew: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create # ???? create(????? ? db? ?????) ::wqwqw:, ??? update? none ?? ??
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
      logging.level:
        org.hibernate.type:

